FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties : 
        id:
            expose: true
            groups: [user_details, user_list]        
        username : 
            expose : true
            groups : [user_details, user_list]
        email:
            expose: true
            groups: [user_details, user_list]
        enabled:
            expose: true
            groups: [user_details]
        locked:
            expose: true
            groups: [user_details]
        roles:
            expose: true
            groups: [user_details]
        
        
        