blogger_user:
    resource: "@BloggerUserBundle/Resources/config/routing.yml"
    prefix:   /

blogger_blog:
    type: rest
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
