blogs:
    type: rest
    resource: Blogger\BlogBundle\Controller\BlogController
    
comments:
    type: rest
    parent: blogs
    resource: Blogger\BlogBundle\Controller\CommentController

translation:
    type: rest
    resource: Blogger\BlogBundle\Controller\TranslateController 