services:
#    blogger_blog.example:
#        class: Blogger\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    blogger_blog.json_handler:
        class: Blogger\BlogBundle\View\JSONViewHandler
    blogger_blog.view_handler:
        parent: fos_rest.view_handler.default
        calls: 
            - ['registerHandler', ['json', [@blogger_blog.json_handler, 'createResponse']]]
    #entity managers
    blogger_blog.blog_manager:
        class: Blogger\BlogBundle\Services\Blog
        arguments:
            - @blogger_blog.blog_repository
    
    blogger_blog.blog_repository:
        class: Blogger\BlogBundle\Repository\BlogRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ BloggerBlogBundle:Blog ]
    
    blogger_blog.kernel.listener.json_request_transformer:
        class: Blogger\BlogBundle\EventListener\JsonRequestTransformer
        tags: 
            - {name : kernel.event_listener, event: kernel.request, method: onKernelRequest}