services:
#    blogger_blog.example:
#        class: Blogger\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    blogger_blog.json_handler:
        class: Blogger\BlogBundle\View\JSONViewHandler
    blogger_blog.view_handler:
        parent: fos_rest.view_handler.default
        calls: 
            - ['registerHandler', ['json', [@blogger_blog.json_handler, 'createResponse']]]
    #entity managers
    blogger_blog.blog_manager:
        class: Blogger\BlogBundle\Services\BlogManager
        calls:
            - ['setClass', ['BloggerBlogBundle:Blog']]
            - ['setEntityManager' , [@doctrine.orm.entity_manager]]
    
    blogger_blog.comment_manager:
        class: Blogger\BlogBundle\Services\CommentManager
        calls:
            - ['setClass', [BloggerBlogBundle:Comment]]
            - ['setEntityManager', [@doctrine.orm.entity_manager]]
    
    blogger_blog.kernel.listener.json_request_transformer:
        class: Blogger\BlogBundle\EventListener\JsonRequestTransformer
        tags: 
            - {name : kernel.event_listener, event: kernel.request, method: onKernelRequest}